namespace Burkardt.Sequence;

public static class Padovan
{
    public static void padovan ( int n, ref int[] p )

        //****************************************************************************80
        //
        //  Purpose:
        //
        //    PADOVAN returns the first N values of the Padovan sequence.
        //
        //  Discussion:
        //
        //    The Padovan sequence has the initial values:
        //
        //      P(0) = 1
        //      P(1) = 1
        //      P(2) = 1
        //
        //    and subsequent entries are generated by the recurrence
        //
        //      P(I+1) = P(I-1) + P(I-2)
        //
        //  Example:
        //
        //    0   1
        //    1   1
        //    2   1
        //    3   2
        //    4   2
        //    5   3
        //    6   4
        //    7   5
        //    8   7
        //    9   9
        //   10  12
        //
        //  Licensing:
        //
        //    This code is distributed under the GNU LGPL license. 
        //
        //  Modified:
        //
        //    11 August 2004
        //
        //  Author:
        //
        //    John Burkardt
        //
        //  Reference:
        //
        //    Ian Stewart,
        //    "A Neglected Number",
        //    Scientific American, Volume 274, pages 102-102, June 1996.
        //
        //    Ian Stewart,
        //    Math Hysteria,
        //    Oxford, 2004.
        //
        //  Parameters:
        //
        //    Input, int N, the number of terms.
        //
        //    Output, int P[N], terms 0 though N-1 of the sequence.
        //
    {
        int i;

        switch (n)
        {
            case < 1:
                return;
        }

        p[0] = 1;

        switch (n)
        {
            case < 2:
                return;
        }

        p[1] = 1;

        switch (n)
        {
            case < 3:
                return;
        }
 
        p[2] = 1;

        for ( i = 4; i <= n; i++ )
        {
            p[i-1] = p[i-3] + p[i-4];
        }
    }
}