# Recommended: only restore/build/test the UnitTests project to avoid platform-specific projects
name: .NET CI (UnitTests only)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: dotnet-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0']  # keep minimal for speed; add more if you want
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore UnitTests
        run: dotnet restore UnitTests/UnitTests.csproj

      - name: Build UnitTests
        run: dotnet build UnitTests/UnitTests.csproj --no-restore --configuration Release

      - name: Run UnitTests
        run: dotnet test UnitTests/UnitTests.csproj --no-build --configuration Release --logger "trx;LogFileName=TestResults.trx" --verbosity normal

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: UnitTests/TestResults/**/*.trx